import React, { useEffect, useState } from 'react';
import { Card, Button, Row, Col } from 'react-bootstrap';
import { LinkContainer } from 'react-router-bootstrap';

const HomeScreen = () => {
  const [pingMsg, setPingMsg] = useState('');

  useEffect(() => {
    fetch('/api/test/ping')
      .then((res) => res.json())
      .then((data) => setPingMsg(data.message))
      .catch((err) => console.error('Ping failed ❌', err));
  }, []);

  return (
    <>
      <p style={{ color: 'green' }}>{pingMsg}</p>

      <div>
        <h1 className="mb-4">Smart Delivery Dashboard</h1>
        <Row className="g-4">
          <Col md={6} lg={3}>
            <Card className="h-100">
              <Card.Body>
                <Card.Title>Live Tracking</Card.Title>
                <Card.Text>Track delivery agents in real time on the map.</Card.Text>
                <LinkContainer to="/live-tracking">
                  <Button variant="primary">View</Button>
                </LinkContainer>
              </Card.Body>
            </Card>
          </Col>

          <Col md={6} lg={3}>
            <Card className="h-100">
              <Card.Body>
                <Card.Title>Demand Forecast</Card.Title>
                <Card.Text>See AI-predicted demand for products by warehouse.</Card.Text>
                <LinkContainer to="/forecast">
                  <Button variant="success">Forecast</Button>
                </LinkContainer>
              </Card.Body>
            </Card>
          </Col>

          <Col md={6} lg={3}>
            <Card className="h-100">
              <Card.Body>
                <Card.Title>Inventory</Card.Title>
                <Card.Text>View real-time inventory per product and warehouse.</Card.Text>
                <LinkContainer to="/inventory">
                  <Button variant="warning">Dashboard</Button>
                </LinkContainer>
              </Card.Body>
            </Card>
          </Col>

          <Col md={6} lg={3}>
            <Card className="h-100">
              <Card.Body>
                <Card.Title>Optimized Routes</Card.Title>
                <Card.Text>Check shortest delivery paths generated by AI.</Card.Text>
                <LinkContainer to="/route-optimizer">
                  <Button variant="dark">Optimize</Button>
                </LinkContainer>
              </Card.Body>
            </Card>
          </Col>
        </Row>
      </div>
    </>
  );
};

export default HomeScreen;

